#!/usr/bin/env bash

set -euo pipefail

source script/env "$@"

count=3
export SKIP_INTEGRATION_TESTS=${SKIP_INTEGRATION_TESTS:-true}

go test -mod=vendor -race -count $count -v -cover -coverprofile=coverage.out ./...
